import { useQuery } from '@tanstack/react-query'
import type { ReactNode } from 'react'
import { getStep1Output } from '../api'
import { AlertIcon, ArrowIcon, CheckIcon, ClockIcon, FileIcon, HeartIcon, UploadIcon } from '../components/icons'
import { ConfidenceBadge, StatusBadge } from '../components/Badges'
import { SectionCard } from '../components/SectionCard'

export function DashboardPage() {
  const { data: output } = useQuery({ queryKey: ['step1-output'], queryFn: () => getStep1Output('job_ocr_771') })
  const reviewCount = output?.extracted_fields.filter((field) => field.requires_doctor_review_before_memory_write).length ?? 0
  return <div className="page-stack">
    <div className="dashboard-welcome"><div><p className="eyebrow">MONDAY, 17 AUGUST 2026</p><h1>Good morning, Dr. Mehta <span>✦</span></h1><p className="page-subtitle">Here’s the clinical overview for your workspace.</p></div><div className="date-chip"><ClockIcon /> Today <span>⌄</span></div></div>
    <div className="kpi-grid"><Kpi label="Today's consultations" value="12" detail="3 remaining" tone="teal" icon={<HeartIcon />} /><Kpi label="Patients needing review" value={String(reviewCount || 4)} detail="2 high priority" tone="amber" icon={<AlertIcon />} /><Kpi label="High-risk conflicts" value="2" detail="Requires attention" tone="red" icon={<ActivityMini />} /><Kpi label="Clinical drafts" value="6" detail="1 ready to finalize" tone="blue" icon={<FileIcon />} /></div>
    <div className="dashboard-grid"><SectionCard title="Recent uploads" eyebrow="INPUT PROCESSING" action={<a href="/upload" className="text-link">View all <ArrowIcon /></a>}><div className="upload-list"><UploadItem name="Ananya Mehta" document={output?.source_document ?? 'Ananya_Mehta_prescription.jpg'} status={output?.processing_status ?? 'pending_human_verification'} time="12 min ago" initials="AM" /><UploadItem name="Vikram Singh" document="Lab_Report_2026-08-17.pdf" status="complete" time="34 min ago" initials="VS" /><UploadItem name="Sara Thomas" document="Discharge_Note_0817.pdf" status="complete" time="1 hr ago" initials="ST" /></div></SectionCard><SectionCard title="Review attention" eyebrow="PHYSICIAN QUEUE" action={<a href="/review-queue" className="text-link">Open queue <ArrowIcon /></a>}><div className="attention-card"><div className="attention-icon"><AlertIcon /></div><div><strong>{reviewCount || 4} fields need your review</strong><p>Some information needs physician review before it can be added to the patient record.</p></div><a href="/verification" className="round-arrow"><ArrowIcon /></a></div><div className="mini-review-list">{output?.extracted_fields.slice(0, 3).map((field) => <div className="mini-review" key={field.field_id}><span className="mini-field-dot" /><span>{field.field_type.replaceAll('_', ' ')}</span><ConfidenceBadge field={field} /></div>)}</div></SectionCard></div>
    <div className="quick-actions"><div><p className="eyebrow">QUICK ACTIONS</p><h2>Move the work forward</h2></div><a className="quick-action" href="/upload"><span><UploadIcon /></span><strong>Upload clinical document</strong><ArrowIcon /></a><a className="quick-action" href="/review-queue"><span><CheckIcon /></span><strong>Review pending items</strong><ArrowIcon /></a><a className="quick-action" href="/memory"><span><HeartIcon /></span><strong>Open patient memory</strong><ArrowIcon /></a></div>
  </div>
}
function Kpi({ label, value, detail, tone, icon }: { label: string; value: string; detail: string; tone: string; icon: ReactNode }) { return <div className="kpi-card"><div className={`kpi-icon ${tone}`}>{icon}</div><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className={`kpi-detail ${tone}`}><span className="trend-line">↗</span> {detail}</div></div> }
function UploadItem({ name, document, status, time, initials }: { name: string; document: string; status: 'complete' | 'pending_human_verification' | 'failed'; time: string; initials: string }) { return <div className="upload-item"><div className="mini-avatar">{initials}</div><div className="upload-item-main"><strong>{name}</strong><span><FileIcon /> {document}</span></div><div className="upload-item-status"><StatusBadge status={status} /><small>{time}</small></div></div> }
function ActivityMini() { return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 12h4l2.2-7 4.1 14L16 12h5" /></svg> }
