import { useMemo, useState } from 'react'
import type { MemoryFact } from '../contracts/memory'
import type { Conflict, RetrievedContext } from '../contracts/retrievedContext'
import { useApproveTier3, useConflictList, useMemoryEvents, useRejectTier3, useResolveConflict, useRetrievedContext } from '../hooks/useMemory'
import { TrustTierBadge } from '../components/Badges'
import { MemoryFactCard } from '../components/MemoryFactCard'
import { MemoryProvenanceDrawer } from '../components/MemoryProvenanceDrawer'
import { SectionCard } from '../components/SectionCard'
import { AlertIcon, ArrowIcon, CheckIcon, ClockIcon, HeartIcon, SearchIcon, XIcon } from '../components/icons'

type MemoryView = 'explorer' | 'timeline' | 'conflicts'
const contextCategories = ['conditions', 'medications', 'allergies', 'procedures', 'lab_trends', 'significant_events'] as const
const categoryLabels: Record<typeof contextCategories[number], string> = { conditions: 'Conditions', medications: 'Medications', allergies: 'Allergies', procedures: 'Procedures', lab_trends: 'Laboratory trends', significant_events: 'Significant events' }

export function MemoryExplorerPage({ initialView = 'explorer' }: { initialView?: MemoryView }) {
  const [view, setView] = useState<MemoryView>(initialView)
  const [query, setQuery] = useState('chest pain')
  const [patientId, setPatientId] = useState('pat_00123')
  const [encounterId, setEncounterId] = useState('enc_2026_0817_01')
  const [selectedFact, setSelectedFact] = useState<MemoryFact | null>(null)
  const [approvedIds, setApprovedIds] = useState<string[]>([])
  const [rejectedIds, setRejectedIds] = useState<string[]>([])
  const [resolvedIds, setResolvedIds] = useState<string[]>([])
  const queryConcepts = query.split(',').map((concept) => concept.trim()).filter(Boolean)
  const { data: context, isLoading } = useRetrievedContext(queryConcepts, patientId, encounterId)
  const { data: timeline = [] } = useMemoryEvents()
  const { data: conflicts = [] } = useConflictList()
  const approve = useApproveTier3(); const reject = useRejectTier3(); const resolve = useResolveConflict()
  const displayedContext = applyTierActions(context, approvedIds, rejectedIds)
  const allFacts = useMemo(() => displayedContext ? flattenContext(displayedContext) : [], [displayedContext])
  const approveFact = (fact: MemoryFact) => { setApprovedIds((ids) => [...ids, fact.event_id]); approve.mutate({ eventId: fact.event_id, physicianId: 'phy_04' }) }
  const rejectFact = (fact: MemoryFact) => { setRejectedIds((ids) => [...ids, fact.event_id]); reject.mutate({ eventId: fact.event_id, physicianId: 'phy_04' }) }
  const resolveConflict = (conflictId: string, action: 'confirm_event_a' | 'confirm_event_b' | 'keep_unresolved') => { setResolvedIds((ids) => [...ids, conflictId]); resolve.mutate({ conflictId, request: { resolution_action: action, physician_id: 'phy_04' } }) }
  return <div className="page-stack"><PatientMemoryHeader patientId={patientId} encounterId={encounterId} onPatientIdChange={setPatientId} onEncounterIdChange={setEncounterId} /><div className="memory-nav"><button className={view === 'explorer' ? 'active' : ''} onClick={() => setView('explorer')}><HeartIcon /> Patient memory</button><button className={view === 'timeline' ? 'active' : ''} onClick={() => setView('timeline')}><ClockIcon /> Patient timeline</button><button className={view === 'conflicts' ? 'active' : ''} onClick={() => setView('conflicts')}><AlertIcon /> Clinical conflicts{displayedContext && displayedContext.conflicts.length > 0 && <span>{displayedContext.conflicts.length}</span>}</button><div className="append-only-note"><span className="append-dot" /> History is append-only</div></div>{view !== 'conflicts' && <RetrievalBar query={query} setQuery={setQuery} patientId={patientId} encounterId={encounterId} />}{isLoading ? <div className="empty-loading">Loading patient history…</div> : view === 'explorer' ? <ExplorerView context={displayedContext} allFacts={allFacts} onFactClick={setSelectedFact} onApprove={approveFact} onReject={rejectFact} /> : view === 'timeline' ? <TimelineView events={timeline} onFactClick={setSelectedFact} /> : <ConflictCenter conflicts={conflicts} resolvedIds={resolvedIds} onResolve={resolveConflict} onFactClick={setSelectedFact} />}{selectedFact && <MemoryProvenanceDrawer fact={selectedFact} onClose={() => setSelectedFact(null)} />}</div>
}
function PatientMemoryHeader({ patientId, encounterId, onPatientIdChange, onEncounterIdChange }: { patientId: string; encounterId: string; onPatientIdChange: (value: string) => void; onEncounterIdChange: (value: string) => void }) { return <div className="memory-header"><div className="patient-profile-large"><div className="patient-avatar-large">AM</div><div><p className="eyebrow">PATIENT MEMORY</p><h1>Ananya Mehta</h1><p>32 years · Female · <span className="patient-status"><span /> Active patient</span></p></div></div><div className="patient-identifiers"><label>Patient ID<input value={patientId} onChange={(event) => onPatientIdChange(event.target.value)} /></label><label>Encounter ID<input value={encounterId} onChange={(event) => onEncounterIdChange(event.target.value)} /></label></div></div> }
function RetrievalBar({ query, setQuery, patientId, encounterId }: { query: string; setQuery: (value: string) => void; patientId: string; encounterId: string }) { return <SectionCard title="Search patient context" eyebrow="PATIENT HISTORY" action={<span className="retrieval-contract">Patient context</span>} className="retrieval-card"><div className="retrieval-form"><label>Ask about this patient's history<div className="retrieval-input"><SearchIcon /><input aria-label="Ask about this patient's history" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="What medications is this patient currently taking?" /></div></label><div className="retrieval-param"><span>Patient</span><strong>{patientId}</strong></div><div className="retrieval-param"><span>Encounter</span><strong>{encounterId}</strong></div><button className="primary-button"><SearchIcon /> Search patient context</button></div><div className="retrieval-note"><CheckIcon /> Verified information, unverified reports, and conflicting records are kept separate for safe review.</div></SectionCard> }
function ExplorerView({ context, allFacts, onFactClick, onApprove, onReject }: { context?: RetrievedContext; allFacts: MemoryFact[]; onFactClick: (fact: MemoryFact) => void; onApprove: (fact: MemoryFact) => void; onReject: (fact: MemoryFact) => void }) { if (!context) return null; const verifiedCount = contextCategories.reduce((count, key) => count + context.verified_context[key].length, 0); return <><SummaryGrid context={context} /><div className="memory-columns"><SectionCard title="Verified information" eyebrow="SAFE PATIENT HISTORY" action={<span className="verified-heading"><CheckIcon /> {verifiedCount} records</span>}><div className="memory-category-grid">{contextCategories.map((key) => <div className="memory-category" key={key}><div className="memory-category-title"><span>{categoryLabels[key]}</span><strong>{context.verified_context[key].length}</strong></div>{context.verified_context[key].length ? context.verified_context[key].map((fact) => <MemoryFactCard key={fact.event_id} fact={fact} onProvenance={onFactClick} />) : <p className="category-empty">No recorded information</p>}</div>)}</div></SectionCard><div className="memory-side-column"><SectionCard title="Unverified information" eyebrow="REVIEW BEFORE USE" action={<span className="unverified-heading"><AlertIcon /> {context.unverified_information.length} to review</span>}><div className="unverified-list">{context.unverified_information.map((fact) => <MemoryFactCard key={fact.event_id} fact={fact} onProvenance={onFactClick} onApprove={onApprove} onReject={onReject} />)}</div><div className="unverified-note"><AlertIcon /> Unverified information is never merged with verified patient history.</div></SectionCard><SectionCard title="Recent patient history" eyebrow="APPEND-ONLY HISTORY"><div className="activity-mini-list">{allFacts.slice(0, 4).map((fact) => <button key={fact.event_id} onClick={() => onFactClick(fact)}><span className="activity-line" /><div><strong>{fact.normalized_concept}</strong><span>{fact.trust_tier === 3 ? 'Unverified information' : `Verification level ${fact.trust_tier}`} · {new Date(fact.ingestion_timestamp).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}</span></div><ArrowIcon /></button>)}</div></SectionCard></div></div><ConflictPreview conflicts={context.conflicts} onFactClick={onFactClick} /></> }
function SummaryGrid({ context }: { context: RetrievedContext }) { const items: Array<[string, number]> = [['Conditions', context.verified_context.conditions.length], ['Medications', context.verified_context.medications.length], ['Allergies', context.verified_context.allergies.length], ['Procedures', context.verified_context.procedures.length], ['Laboratory trends', context.verified_context.lab_trends.length], ['Conflicting records', context.conflicts.length]]; return <div className="memory-summary-grid">{items.map(([label, count]) => <div key={label} className={label === 'Conflicting records' && count > 0 ? 'memory-summary-card conflict-summary' : 'memory-summary-card'}><span>{label}</span><strong>{count}</strong><small>{label === 'Conflicting records' && count > 0 ? 'Needs review' : 'Current history'}</small></div>)}</div> }
function applyTierActions(context: RetrievedContext | undefined, approvedIds: string[], rejectedIds: string[]): RetrievedContext | undefined { if (!context) return undefined; const promoted = context.unverified_information.filter((fact) => approvedIds.includes(fact.event_id)).map((fact) => ({ ...fact, trust_tier: 2 as const, reviewed_status: 'not_applicable' as const, uiPromoted: true })); return { ...context, unverified_information: context.unverified_information.filter((fact) => !rejectedIds.includes(fact.event_id) && !approvedIds.includes(fact.event_id)), verified_context: { ...context.verified_context, medications: [...context.verified_context.medications, ...promoted] } } }
function flattenContext(context: RetrievedContext): MemoryFact[] { return [...Object.values(context.verified_context).flat(), ...context.unverified_information] }
function TimelineView({ events, onFactClick }: { events: MemoryFact[]; onFactClick: (fact: MemoryFact) => void }) { return <SectionCard title="Patient timeline" eyebrow="IMMUTABLE LONGITUDINAL HISTORY" action={<span className="append-only-badge"><span className="append-dot" /> No records overwritten</span>}><div className="timeline-list">{events.map((event, index) => <div className="timeline-row" key={event.event_id}><div className="timeline-date"><strong>{new Date(event.event_timestamp).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}</strong><span>{new Date(event.event_timestamp).getFullYear()}</span></div><div className="timeline-rail"><span className="timeline-node" />{index < events.length - 1 && <span className="timeline-connector" />}</div><button className="timeline-fact" onClick={() => onFactClick(event)}><div><span className="timeline-kicker">{event.entity_type} · {event.event_id}</span><strong>{event.normalized_concept}</strong><span>{event.medication_attributes.dosage ?? event.medication_attributes.route ?? event.assertion} · {event.clinical_status}</span></div><div className="timeline-right"><TrustTierBadge tier={event.trust_tier} /><span>{Math.round(event.extraction_confidence * 100)}% confidence</span><ArrowIcon /></div></button></div>)}</div><div className="timeline-invariant"><ClockIcon /><span><strong>Append-only history</strong> Dose changes remain separate records: 500 mg → 1000 mg → discontinued.</span></div></SectionCard> }
function ConflictPreview({ conflicts, onFactClick }: { conflicts: Conflict[]; onFactClick: (fact: MemoryFact) => void }) { return <SectionCard title="Clinical conflicts" eyebrow="SAFETY REVIEW" action={<span className="high-risk-label"><AlertIcon /> High-priority conflicts always shown</span>}><div className="conflict-list">{conflicts.slice(0, 1).map((conflict) => <ConflictCard key={conflict.conflict_id} conflict={conflict} onResolve={() => undefined} onFactClick={onFactClick} compact />)}</div>{conflicts.length === 0 && <p className="category-empty">No active clinical conflicts.</p>}</SectionCard> }
function ConflictCenter({ conflicts, resolvedIds, onResolve, onFactClick }: { conflicts: Conflict[]; resolvedIds: string[]; onResolve: (id: string, action: 'confirm_event_a' | 'confirm_event_b' | 'keep_unresolved') => void; onFactClick: (fact: MemoryFact) => void }) { return <SectionCard title="Clinical conflicts" eyebrow="PHYSICIAN DECISION REQUIRED" action={<span className="high-risk-label"><AlertIcon /> High-priority conflicts always shown</span>}><div className="conflict-list">{conflicts.map((conflict) => <ConflictCard key={conflict.conflict_id} conflict={conflict} resolved={resolvedIds.includes(conflict.conflict_id)} onResolve={(action) => onResolve(conflict.conflict_id, action)} onFactClick={onFactClick} />)}</div></SectionCard> }
function ConflictCard({ conflict, resolved = false, onResolve, onFactClick, compact = false }: { conflict: Conflict; resolved?: boolean; onResolve: (action: 'confirm_event_a' | 'confirm_event_b' | 'keep_unresolved') => void; onFactClick: (fact: MemoryFact) => void; compact?: boolean }) { return <article className={`memory-conflict-card ${conflict.risk_level === 'high' ? 'high-risk-conflict' : ''} ${resolved ? 'resolved-conflict' : ''}`}><div className="conflict-header"><div><span className="conflict-kicker">{conflict.conflict_id} · {conflict.concept_thread}</span><h3>{conflict.risk_level === 'high' ? 'High safety priority' : `${conflict.risk_level} safety priority`}</h3></div><span className={`conflict-status ${resolved ? 'resolved' : conflict.status}`}>{resolved ? 'Decision recorded' : conflict.status === 'unresolved' ? 'Needs review' : conflict.status === 'dismissed' ? 'Reviewed — no resolution' : 'Resolved'}</span></div><div className="conflict-facts"><ConflictFact fact={conflict.event_a} label="Record 1" onClick={() => onFactClick(conflict.event_a)} /><div className="conflict-vs">VS</div><ConflictFact fact={conflict.event_b} label="Record 2" onClick={() => onFactClick(conflict.event_b)} /></div>{!compact && !resolved && <div className="conflict-actions"><button onClick={() => onResolve('confirm_event_a')}><CheckIcon /> Confirm record 1</button><button onClick={() => onResolve('confirm_event_b')}><CheckIcon /> Confirm record 2</button><button onClick={() => onResolve('keep_unresolved')}><XIcon /> Keep unresolved</button></div>}</article> }
function ConflictFact({ fact, label, onClick }: { fact: MemoryFact; label: string; onClick: () => void }) { return <button className="conflict-fact" onClick={onClick}><span>{label} · {fact.trust_tier === 3 ? 'Unverified information' : `Verification level ${fact.trust_tier}`}</span><strong>{fact.normalized_concept}</strong><small>{fact.assertion} · {fact.clinical_status} · {fact.source_document_id}</small><TrustTierBadge tier={fact.trust_tier} /></button> }
