import type { MemoryFact } from '../contracts/memory'
import { TrustTierBadge } from './Badges'
import { AlertIcon, ArrowIcon, CheckIcon, FileIcon } from './icons'
import { formatConfidence } from '../lib/confidence'

export function MemoryFactCard({ fact, onProvenance, onApprove, onReject, promoted: requestedPromoted }: { fact: MemoryFact; onProvenance: (fact: MemoryFact) => void; onApprove?: (fact: MemoryFact) => void; onReject?: (fact: MemoryFact) => void; promoted?: boolean }) {
  const promotedInContext = requestedPromoted || Boolean((fact as MemoryFact & { uiPromoted?: boolean }).uiPromoted)
  const tier = promotedInContext ? 2 : fact.trust_tier
  return <article className={`memory-fact-card ${fact.trust_tier === 3 && !promotedInContext ? 'unverified-fact' : ''}`}><div className="memory-fact-top"><div><div className="memory-fact-kicker"><span>{fact.entity_type}</span><span className="memory-event-id">{fact.event_id}</span></div><h3>{fact.normalized_concept}</h3></div><div className="memory-fact-badges"><TrustTierBadge tier={tier} />{promotedInContext && <span className="tier-transition"><span>Unverified information</span><ArrowIcon /><strong>Physician-approved</strong></span>}</div></div><div className="memory-fact-grid"><MemoryDetail label="Clinical record group" value={fact.concept_thread_id} mono /><MemoryDetail label="Standardized clinical concept" value={fact.snomed_ct_id ?? 'Not mapped'} mono /><MemoryDetail label="Clinical finding" value={fact.assertion} /><MemoryDetail label="Status" value={fact.clinical_status} /><MemoryDetail label="Time context" value={fact.temporal_context} /><MemoryDetail label="Concept match" value={fact.thread_match_confidence} /></div>{fact.medication_attributes.dosage || fact.medication_attributes.frequency || fact.medication_attributes.route ? <div className="memory-attributes"><span>Medication details</span><strong>{[fact.medication_attributes.dosage, fact.medication_attributes.frequency, fact.medication_attributes.route].filter(Boolean).join(' · ')}</strong></div> : null}{fact.lab_attributes && (fact.lab_attributes.test_name || fact.lab_attributes.value) ? <div className="memory-attributes"><span>Laboratory result</span><strong>{[fact.lab_attributes.test_name, fact.lab_attributes.value, fact.lab_attributes.unit].filter(Boolean).join(' ')}</strong></div> : null}<div className="memory-fact-footer"><span><FileIcon /> Source information · {formatConfidence(fact.extraction_confidence)} extraction confidence</span><div className="memory-fact-actions"><button className="provenance-button" onClick={() => onProvenance(fact)}>Source & verification <ArrowIcon /></button>{fact.trust_tier === 3 && !promotedInContext && onApprove && onReject ? <><button className="fact-reject" onClick={() => onReject(fact)}><AlertIcon /> Reject</button><button className="fact-approve" onClick={() => onApprove(fact)}><CheckIcon /> Approve</button></> : null}</div></div></article>
}
function MemoryDetail({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div><span>{label}</span><strong className={mono ? 'memory-mono' : ''}>{value}</strong></div> }
