import { useState } from 'react'
import { useStep1Output, useVerifyStep1Field } from '../hooks/useStep1'
import { AlertIcon, CheckIcon, FileIcon, XIcon } from '../components/icons'
import { ConfidenceBadge, RiskBadge } from '../components/Badges'
import { SectionCard } from '../components/SectionCard'
import type { ExtractedField } from '../contracts/step1Output'
import { useWorkflow } from '../context/WorkflowContext'
import { useAuth } from '../context/AuthContext'

export function VerificationPage() { const { workflow } = useWorkflow(); const { data: output } = useStep1Output(workflow.document_id); const [selectedId, setSelectedId] = useState<string | null>(null); const selected = output?.extracted_fields.find((field) => field.field_id === selectedId) ?? output?.extracted_fields.find((field) => field.requires_doctor_review_before_memory_write); if (!output) return <div className="empty-loading">Loading verification record…</div>; return <div className="page-stack"><div className="page-heading"><div><p className="eyebrow">PHYSICIAN REVIEW</p><h1>Review & correct extracted information</h1><p className="page-subtitle">Review uncertain information, correct the extracted value when needed, and confirm it against the original source.</p></div><div className="safety-pill"><AlertIcon /> Unverified information is blocked</div></div><div className="verification-grid"><SectionCard title="Source document" eyebrow="ORIGINAL INPUT" className="document-preview"><div className="document-toolbar"><span><FileIcon /> {output.source_document ?? output.document_id}</span><span>Page 1 / 1</span></div><div className="document-sheet"><div className="document-stamp">MEDFLOW SCAN</div><p>{output.original_language_text ?? 'Original source text preserved for review.'}</p><p>Clinical information requiring physician review</p><div className="highlight-box">{selected?.raw_text ?? 'Select information to inspect'}</div></div><div className="document-caption">Original source preserved · {output.source_language.toUpperCase()} · {Math.round((output.translation_confidence ?? 0) * 100)}% translation confidence</div></SectionCard><SectionCard title="Extracted information" eyebrow={`${output.extracted_fields.length} ITEMS · ${output.patient_id}`} className="field-review-card"><div className="field-review-list">{output.extracted_fields.map((field) => <FieldReviewItem key={field.field_id} field={field} selected={field.field_id === selected?.field_id} onSelect={() => setSelectedId(field.field_id)} />)}</div>{selected && <VerificationActions key={selected.field_id} field={selected} documentId={output.document_id} />}</SectionCard></div><div className="safety-banner"><div className="safety-banner-icon"><AlertIcon /></div><div><strong>Unverified information cannot be added to the patient record.</strong><span>Only automatically cleared or physician-confirmed information can proceed.</span></div></div></div> }
function FieldReviewItem({ field, selected, onSelect }: { field: ExtractedField; selected: boolean; onSelect: () => void }) { return <button className={`field-review-item ${selected ? 'selected' : ''}`} onClick={onSelect}><div className="field-review-heading"><span className="field-type">{field.field_type.replace(/_/g, ' ')}</span><RiskBadge highRisk={field.is_high_risk_field} /></div><div className="field-review-values"><span>{field.raw_text}</span><b>→</b><strong>{field.standardized_text}</strong></div><div className="field-review-meta"><ConfidenceBadge field={field} /><span className="review-state">{field.review_status === 'approved' ? <><CheckIcon /> Approved</> : <><AlertIcon /> Needs review</>}</span><span className="field-edit-hint">Edit value</span></div></button> }
function VerificationActions({ field, documentId }: { field: ExtractedField; documentId: string }) { const { user } = useAuth(); const [text, setText] = useState(field.verified_text ?? field.standardized_text); const [editing, setEditing] = useState(false); const [corrected, setCorrected] = useState(false); const verify = useVerifyStep1Field(); const saveCorrection = () => { setCorrected(true); setEditing(false) }; const cancelCorrection = () => { setText(field.verified_text ?? field.standardized_text); setEditing(false) }; const submit = (approved: boolean) => { if (!user?.id) return; verify.mutate({ document_id: documentId, field_id: field.field_id, verified_text: text, reviewer_id: user.id, approved }) }; return <div className="verification-actions"><div className="correction-source"><span>Original source</span><strong>{field.raw_text}</strong></div>{editing ? <label>Physician correction<input aria-label="Physician correction" value={text} onChange={(event) => setText(event.target.value)} /></label> : <div className="correction-current"><span>Current extracted value</span><strong>{text}</strong></div>}{!editing && !verify.isSuccess && <button className="secondary-button edit-value-button" onClick={() => setEditing(true)}>Edit value</button>}{editing && <div className="action-row"><button className="secondary-button" onClick={cancelCorrection}>Cancel</button><button className="confirm-button" onClick={saveCorrection} disabled={!text.trim()}><CheckIcon /> Save correction</button></div>}{corrected && <p className="success-copy"><CheckIcon /> Physician corrected</p>}<div className="action-row"><button className="reject-button" onClick={() => submit(false)} disabled={verify.isPending}><XIcon /> Reject</button><button className="confirm-button" onClick={() => submit(true)} disabled={verify.isPending || !text.trim() || !user?.id}><CheckIcon /> Confirm and allow</button></div>{verify.isSuccess && <p className="success-copy"><CheckIcon /> Review saved. Patient record access updated.</p>}</div> }
